#==============================
#config_cam_baseline.yaml
#==============================

diag_basic_info:

    compare_obs: false
    create_html: true
    obs_data_loc: /glade/work/nusbaume/SE_projects/model_diagnostics/ADF_obs
    cam_regrid_loc: /glade/scratch/hannay/ADF/climos-regrid/
    cam_overwrite_regrid: false
    cam_diag_plot_loc: /glade/scratch/hannay/ADF/plots/ 
    use_defaults: true
    plot_press_levels: [ ]
    central_longitude: 180
    weight_season: True
    num_procs: 8
    redo_plot: false

#==============================

diag_cam_climo:

    calc_cam_climo: true
    cam_overwrite_climo: false
    cam_case_name: b.cesm3_cam058_mom_e.B1850WscMOM.ne30_L58_t061.camdev_cice5.024
    cam_hist_loc: /glade/scratch/hannay/archive/${diag_cam_climo.cam_case_name}/atm/hist/
    start_year: 1
    end_year: 10
    cam_climo_loc:  /glade/work/hannay/ADF/climos/${diag_cam_climo.cam_case_name}/yrs_${diag_cam_climo.start_year}-${diag_cam_climo.end_year}
    cam_ts_done: true
    cam_ts_save: true
    cam_overwrite_ts: false
    cam_ts_loc: /glade/scratch/hannay/ADF/timeseries/${diag_cam_climo.cam_case_name} 
   
#==============================

diag_cam_baseline_climo:

    calc_cam_climo: true
    cam_overwrite_climo: false
    cam_case_name: b.cesm3_cam058_mom_e.B1850WscMOM.ne30_L58_t061.camdev_cice5.023
    cam_hist_loc: /glade/scratch/hannay/archive/${diag_cam_baseline_climo.cam_case_name}/atm/hist/
    start_year: 1
    end_year: 10
    cam_climo_loc: /glade/work/hannay/ADF/climos/${diag_cam_baseline_climo.cam_case_name}/yrs_${diag_cam_baseline_climo.start_year}-${diag_cam_baseline_climo.end_year}
    cam_ts_done: true
    cam_ts_save: true
    cam_overwrite_ts: false
    cam_ts_loc: /glade/scratch/hannay/ADF/timeseries/${diag_cam_baseline_climo.cam_case_name} 

#==============================

diag_cvdp_info:

    cvdp_run: false
    cvdp_codebase_loc: /glade/u/home/asphilli/CESM-diagnostics/CVDP/Release/v5.2.0/
    cvdp_loc: /glade/scratch/asphilli/ADF-Sandbox/cvdp/      #MUST EDIT!
    cvdp_tar: false

#+++++++++++++++++++++++++++++++++++++++++++++++++++
#These variables below only matter if you are using
#a non-standard method, or are adding your own
#diagnostic scripts.
#+++++++++++++++++++++++++++++++++++++++++++++++++++

#Note:  If you want to pass arguments to a particular script, you can
#do it like so (using the "averaging_example" script in this case):
# - {create_climo_files: {kwargs: {clobber: true}}}

#Name of time-averaging scripts being used to generate climatologies.
#These scripts must be located in "scripts/averaging":
time_averaging_scripts:
    - create_climo_files

#Name of regridding scripts being used.
#These scripts must be located in "scripts/regridding":
regridding_scripts:
    - regrid_and_vert_interp

#List of analysis scripts being used.
#These scripts must be located in "scripts/analysis":
analysis_scripts:
    - amwg_table

#List of plotting scripts being used.
#These scripts must be located in "scripts/plotting":
plotting_scripts:
    - global_latlon_map
    - global_latlon_vect_map
    - zonal_mean
    - meridional_mean
    - polar_map
    - cam_taylor_diagram
#    - qbo 

#List of CAM variables that will be processesd:
#If CVDP is to be run PSL, TREFHT, TS and PRECT (or PRECC and PRECL) should be listed
diag_var_list:                                                                                                                                                                                                         
   - AODDUST                                                                                                                                                                                                                
   - AODVIS                                                                                                                                                                                                                                                                                                                                                                                   
   - CLDHGH                                                                                                                                                                                                             
   - CLDICE                                                                                                                                                                                                             
   - CLDLIQ                                                                                                                                                                                                             
   - CLDLOW                                                                                                                                                                                                             
   - CLDMED                                                                                                                                                                                                             
   - CLDTOT                                                                                                                                                                                                             
   - CLOUD                                                                                                                                                                                                                                                                                                                                                                                   
   - FLNS                                                                                                                                                                                                                                            
   - FLNT
   - FLNTC
   - FSNS
   - FSNT
   - FSNTC
   - LHFLX
   - LWCF
   - OMEGA500
   - PBLH
   - PRECT
   - PS
   - PSL
   - QFLX
   - RELHUM
   - SHFLX
   - SST
   - SWCF
   - T
   - TAUX
   - TAUY
   - TGCLDIWP
   - TGCLDLWP
   - TMQ
   - TREFHT
   - TS
   - U
   - U10
   - ICEFRAC
   - OCNFRAC
   - LANDFRAC

#<Add more variables here.>

#END OF FILE
